# Generated by Django 2.2.5 on 2020-12-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ziyingyong', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='peopelinfo',
            table='peopleinfo1',
        ),
    ]
