# Generated by Django 2.2.5 on 2020-12-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ziyingyong', '0002_auto_20201224_0950'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='peopelinfo',
            table='peopleinfo',
        ),
    ]
